version: '3.8'

services:
  vite-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app  # Mount the current directory inside the container
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
    command: ["npm", "run", "dev"]
